"""Model registry.

Importing every model here is what populates `Base.metadata`. Alembic's env.py, the
RLS migration helper and `tests/test_tenant_isolation.py` all enumerate the metadata,
so a model that is never imported is a table that is never migrated, never gets an
RLS policy, and is never checked for tenant scoping. Add new models here.
"""

from app.db.base import Base, TenantScoped
from app.models.audit import ActorKind, AuditLog
from app.models.tenant import Tenant, TenantSettings, TenantStatus
from app.models.user import AccountDirectory, PlatformAdmin, User, UserStatus
from app.modules.admin.models import (
    Channel,
    DeliveryState,
    Job,
    JobState,
    Notification,
    NotificationChannelConfig,
    NotificationDelivery,
    NotificationKind,
)
from app.modules.advertising.models import (
    AdContract,
    AdSpot,
    ContractPaymentStatus,
    ContractStatus,
    SpotStatus,
    SpotType,
)
from app.modules.gateway.models import IntegrationPartner
from app.modules.payments.models import (
    PaymentProvider,
    PaymentProviderConfig,
    ProviderMode,
)
from app.modules.booking.models import (
    Booking,
    BookingEvent,
    BookingEventKind,
    BookingStatus,
    BookingType,
    Court,
    Customer,
    Equipment,
    EquipmentCondition,
    EquipmentMovement,
    Gender,
    MemberType,
    MembershipTier,
    MovementKind,
    PaymentStatus,
    Sport,
)
from app.modules.academy.models import (
    Attendance,
    AttendanceStatus,
    Batch,
    BatchStatus,
    Coach,
    CoachingSession,
    CoachSport,
    CoachStatus,
    CoachType,
    EnrollmentStatus,
    Program,
    SessionStatus,
    Student,
    StudentEnrollment,
    StudentStatus,
)
from app.modules.finance.models import (
    CounterKind,
    DocumentCounter,
    Invoice,
    InvoiceStatus,
    MembershipPlan,
    MemberSubscription,
    Payment,
    PaymentMethod,
    PaymentState,
    PlanDuration,
    SubscriptionStatus,
)

__all__ = [
    "AccountDirectory",
    "ActorKind",
    "AdContract",
    "AdSpot",
    "Channel",
    "Attendance",
    "AttendanceStatus",
    "AuditLog",
    "Base",
    "Batch",
    "BatchStatus",
    "Booking",
    "BookingEvent",
    "BookingEventKind",
    "BookingStatus",
    "BookingType",
    "Coach",
    "CoachSport",
    "CoachStatus",
    "CoachType",
    "CoachingSession",
    "ContractPaymentStatus",
    "ContractStatus",
    "CounterKind",
    "Court",
    "Customer",
    "Equipment",
    "EquipmentCondition",
    "EquipmentMovement",
    "DeliveryState",
    "DocumentCounter",
    "EnrollmentStatus",
    "Gender",
    "IntegrationPartner",
    "Invoice",
    "Job",
    "JobState",
    "InvoiceStatus",
    "MemberSubscription",
    "MemberType",
    "MembershipPlan",
    "MembershipTier",
    "MovementKind",
    "Payment",
    "PaymentMethod",
    "PaymentProvider",
    "PaymentProviderConfig",
    "PaymentState",
    "ProviderMode",
    "Notification",
    "NotificationChannelConfig",
    "NotificationDelivery",
    "NotificationKind",
    "PaymentStatus",
    "PlanDuration",
    "PlatformAdmin",
    "Program",
    "SessionStatus",
    "Sport",
    "SpotStatus",
    "SpotType",
    "Student",
    "StudentEnrollment",
    "StudentStatus",
    "SubscriptionStatus",
    "Tenant",
    "TenantScoped",
    "TenantSettings",
    "TenantStatus",
    "User",
    "UserStatus",
]
